# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0002_auto_20161104_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetype',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='usage_type_owners', to=settings.AUTH_USER_MODEL, verbose_name='Owners of usage type'),
        ),
        migrations.AddField(
            model_name='usagetype',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of usage (e.g. bytes, MB, miliseconds, U, etc.)', max_length=32, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='usagetype',
            name='upload_freq',
            field=models.PositiveIntegerField(choices=[(1, 'day'), (2, 'week'), (3, 'month')], default=1, verbose_name='Expected frequency of uploads'),
        ),
    ]
