# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0003_auto_20161118_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetype',
            name='change_tolerance',
            field=models.FloatField(default=0.2, help_text='If the relative change (as in: (d1-d2)/d2) between two consecutive days is higher than this value, then the owners of this usage type will be notified about such (unusual) change.'),
        ),
        migrations.AddField(
            model_name='usagetype',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='usage_type_owners', to=settings.AUTH_USER_MODEL, verbose_name='Owners of usage type'),
        ),
        migrations.AddField(
            model_name='usagetype',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of usage (e.g. bytes, MB, miliseconds, U, etc.)', max_length=32, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='usagetype',
            name='upload_freq',
            field=models.PositiveIntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=1, help_text='Please note that this value doesn\'t affect costs calculation at all - it\'s just for notifications about "holes" detected in your uploads. Remember that have to upload your usages for every day, despite what you\'ve selected here!', verbose_name='Expected frequency of uploads'),
        ),
    ]
