# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0006_copy_ipinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamcost',
            unique_together=set([('team', 'start', 'end')]),
        ),
    ]
