# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0007_team_costs_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAnomalyAck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_date', models.DateField()),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ralph_scrooge.UsageType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usageanomalyack',
            unique_together=set([('type', 'anomaly_date', 'acknowledged_by')]),
        ),
    ]
