# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0008_anomaly_ack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='database_id',
            field=models.IntegerField(null=True, verbose_name='Ralph database ID (obsolete)'),
        ),
    ]
