# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0008_anomaly_ack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseusage',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dynamicextracosttype',
            options={'ordering': ['name'], 'verbose_name': 'Dynamic extra cost', 'verbose_name_plural': 'Dynamic extra costs'},
        ),
        migrations.AlterModelOptions(
            name='extracosttype',
            options={'ordering': ['name'], 'verbose_name': 'extra cost type', 'verbose_name_plural': 'extra cost types'},
        ),
        migrations.AlterModelOptions(
            name='scroogeuser',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='usagetype',
            options={'ordering': ['name'], 'verbose_name': 'usage type', 'verbose_name_plural': 'usage types'},
        ),
    ]
