# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0010_auto_20170510_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetype',
            name='allow_no_daily_usage',
            field=models.BooleanField(default=False, help_text='Skip validation of this UsageType for existing DailyUsages beforerecalculating costs'),
        ),
    ]
