# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0012_auto_20171024_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycost',
            name='pricing_object',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='ralph_scrooge.PricingObject', verbose_name='pricing object'),
        ),
        migrations.AlterField(
            model_name='dailycost',
            name='service_environment',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='ralph_scrooge.ServiceEnvironment', verbose_name='service environment'),
        ),
        migrations.AlterField(
            model_name='dailycost',
            name='type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='ralph_scrooge.BaseUsage', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='dailycost',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='ralph_scrooge.Warehouse', verbose_name='warehouse'),
        ),
    ]
