# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0012_auto_20171024_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackOfficeAssetInfo',
            fields=[
                ('pricingobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ralph_scrooge.PricingObject')),
                ('sn', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='serial number')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='barcode')),
                ('ralph3_asset_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='asset id (Ralph 3)')),
            ],
            options={
                'abstract': False,
            },
            bases=('ralph_scrooge.pricingobject',),
        ),
        migrations.CreateModel(
            name='DailyBackOfficeAssetInfo',
            fields=[
                ('dailypricingobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ralph_scrooge.DailyPricingObject')),
                ('depreciation_rate', models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Depreciation rate')),
                ('is_depreciated', models.BooleanField(default=False, verbose_name='Is depreciated')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='price')),
                ('daily_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='daily cost')),
                ('asset_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_info_set', to='ralph_scrooge.BackOfficeAssetInfo', verbose_name='daily asset details')),
            ],
            options={
                'verbose_name': 'Daily Back Office Asset info',
                'verbose_name_plural': 'Daily Back Office Assets info',
            },
            bases=('ralph_scrooge.dailypricingobject',),
        ),
    ]
