# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ralph_scrooge', '0015_auto_20180202_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='cost')),
                ('forecast_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=16, verbose_name='forecast cost')),
                ('start', models.DateField(blank=True, default=None, null=True, verbose_name='start time')),
                ('end', models.DateField(blank=True, default=None, null=True, verbose_name='end time')),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional information.', verbose_name='Remarks')),
                ('licence_id', models.IntegerField()),
                ('extra_cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ralph_scrooge.ExtraCostType', verbose_name='type')),
                ('pricing_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ralph_scrooge.PricingObject')),
            ],
        ),
    ]
