# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.define "scrooge" do |scrooge|
  end
  config.vm.provider "virtualbox" do |v|
      v.name = "scrooge"
      v.memory = 2048
      v.cpus = 2
  end
  config.vm.provision :shell do |shell|
     shell.path = "provision.sh"
     shell.privileged = true
  end
  config.vm.synced_folder '../', '/home/vagrant/sources/ralph_scrooge/'
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 9181, host: 9181  # rq-dashboard
  config.vm.network "private_network", ip: "192.168.1.101"
end
